In [1]:
import sys, os, math, random
os.getcwd()

'/workspaces/pyt_begin'

In [ ]:
print(sys.platform)

linux

In [2]:
sys.path

['/usr/local/python/3.12.1/lib/python312.zip',
 '/usr/local/python/3.12.1/lib/python3.12',
 '/usr/local/python/3.12.1/lib/python3.12/lib-dynload',
 '',
 '/home/codespace/.local/lib/python3.12/site-packages',
 '/usr/local/python/3.12.1/lib/python3.12/site-packages']

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
import math #### все функции
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, roc_curve
from IPython.display import display, HTML
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier

from sympy import *

import mpl_toolkits.mplot3d as p3
import random
import time


from functools import partial
from ipywidgets import interact, RadioButtons, IntSlider, FloatSlider, Dropdown, BoundedFloatText
from numpy.linalg import norm

from scipy import sparse

random.seed(42) # начальное состояние генератора случайных чисел, чтобы можно было воспроизводить результаты.

#!unzip «путь_до_архива»
#Всё извлечётся в память Colab.

In [ ]:
!pip install theano
!pip install tensorflow

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

\\\\\загрузка файла с гугл диска

In [ ]:
file_path = '/content/drive/My Drive/dataset_209770_6 (1).txt'
with open(file_path, 'r') as file:
    data = file.read()

In [ ]:
%cd /content/drive/My Drive/Colab Notebooks
!ls # Отображение содержимого папки
#!cp source_path destination_path # Копирование файлов

/content/drive/My Drive/Colab Notebooks
'Book Mark_Lutts.ipynb'  'pyt begin.ipynb'

In [ ]:
titanic_data = pd.read_csv('https://github.com/Ultraluxe25/Karpov-Stepik-Introduction-to-DS-and-ML/raw/main/csv/titanic.csv')

\\\\\сохранение файла

In [ ]:
model.save('/content/drive/My Drive/Colab Notebooks/copy_models/keras_model_epoh5.h5')

In [4]:
import pandas as pd

In [12]:
df1= pd.read_csv('data_data//data1.txt', delimiter='\t')
#df1 = pd.read_csv(r'd:\data\dataset_209770_6 (2).txt', delimiter=' ')

In [13]:
df1

   Номер_студенческого_билета  Результат
0                           1         65
1                           2         72
2                           3         81
3                           4         88
4                           5         65
5                           6         72
6                           7         76
7                           8         88
8                           9         92
9                          10          7

In [44]:
df1['Результат'].var()

np.float64(590.2666666666667)

In [ ]:
df2= pd.read_csv('data_data//data2.txt', delimiter='\t')
df2

In [29]:
df2

    Номер билета Выучил ли его Антон
0              1                  Да
1              2                 Нет
2              3                  Да
3              4                  Да
4              5                 Нет
5              6                  Да
6              7                  Да
7              8                  Да
8              9                 Нет
9             10                  Да
10            11                  Да
11            12                  Да
12            13                  Да

In [31]:
#bilet_izuch = df2.isin["'Выучил ли его Антон' == 'Да'"]
bilet_izuch = df2['Выучил ли его Антон'].values
bilet_izuch

array(['Да', 'Нет', 'Да', 'Да', 'Нет', 'Да', 'Да', 'Да', 'Нет', 'Да',
       'Да', 'Да', '    Да'], dtype=object)

In [ ]:
bilet_all = df2['Номер билета'].count()
bilet_izuch =df2['Номер билета'].count()

print(f"Вероятность успешной сдачи (гулянка): {probability_walk:.2%}")
print(f"Вероятность успешной сдачи (учеба): {probability_study:.2%}")
print(f"Изменение вероятности: {probability_delta:.2%}")

AttributeError: Can only use .str accessor with string values!

In [7]:
# Вероятность правильного прыжка на клавишу
p = 0.01136

# Количество прыжков — нот в мелодии
n = 6

# Расчет вероятности успешного исполнения «Собачий вальс»
probability_dog_waltz = p ** n

# Вывод результата
print(f"Вероятность успешного исполнения 'Собачий вальс': {probability_dog_waltz:.8%}")

Вероятность успешного исполнения 'Собачий вальс': 0.00000000%

In [18]:
df4= pd.read_csv('data_data//timeGnom.txt', delimiter='\t')
df4

    Номер_эльфа  Время_производства_подарка_в_минутах
0             1                                    23
1             2                                    27
2             3                                    25
3             4                                    30
4             5                                    22
5             6                                    28
6             7                                    26
7             8                                    29
8             9                                    24
9            10                                    31
10           11                                    20
11           12                                    32
12           13                                    28
13           14                                    26
14           15                                    30
15           16                                    21
16           17                                    27
17           18                                    29
18           19                                    25
19           20                                    33
20           21                                    22
21           22                                    28
22           23                                    24
23           24                                    31
24           25                                    26
25           26                                    30
26           27                                    23
27           28                                    29
28           29                                    25
29           30                                    32
30           31                                    21
31           32                                    27
32           33                                    26
33           34                                    30
34           35                                    24
35           36                                    28
36           37                                    22
37           38                                    31
38           39                                    25
39           40                                    29

In [9]:
import numpy as np
from scipy.stats import t, ttest_1samp

In [11]:
mean_time = np.mean(df3)
mean_time

np.float64(23.6125)

In [19]:
df3 = df4['Время_производства_подарка_в_минутах']
df3

0     23
1     27
2     25
3     30
4     22
5     28
6     26
7     29
8     24
9     31
10    20
11    32
12    28
13    26
14    30
15    21
16    27
17    29
18    25
19    33
20    22
21    28
22    24
23    31
24    26
25    30
26    23
27    29
28    25
29    32
30    21
31    27
32    26
33    30
34    24
35    28
36    22
37    31
38    25
39    29
Name: Время_производства_подарка_в_минутах, dtype: int64

In [20]:
# Выборочное среднее

mean_time = np.mean(df3)

# Выборочная дисперсия
sigma = np.var(df3, ddof=1)

# 95%-й доверительный интервал для математического ожидания
standard_bias = np.std(df3, ddof=1) / np.sqrt(len(df3))
confidence_interval = t.interval(0.95, len(df3) - 1, mean_time, sigma)

# t-тест
mu_0 = 28  # Предполагаемое среднее время. Вы можете проверить эту или другую гипотезу.
t_statistic, p_value = ttest_1samp(df3, mu_0)

# Вывод результатов
print(f"Выборочное среднее: {mean_time}")
print(f"Выборочная дисперсия: {sigma}")
print(f"95%-й доверительный интервал: {confidence_interval}")
print(f"t-статистика: {t_statistic}")
print(f"p-значение: {p_value}")

Выборочное среднее: 26.725
Выборочная дисперсия: 11.845512820512822
95%-й доверительный интервал: (np.float64(2.7651887747696797), np.float64(50.68481122523032))
t-статистика: -2.3429512208287777
p-значение: 0.02432645725527155

In [21]:

from scipy.stats import pearsonr

# Данные
potions_making = np.array([85, 78, 90, 88, 82, 95])
programming = np.array([90, 82, 92, 86, 80, 94])
time_to_read = np.array([10, 8, 12, 11, 9, 13])

# Коэффициент корреляции Пирсона и p-значение
correlation, p_value = pearsonr(potions_making, programming)
print(f"Коэффициент корреляции Пирсона: {correlation}")
print(f"P-значение: {p_value}")

# Коэффициент корреляции Пирсона и p-значение для времени на чтение
correlation_time, p_value_время = pearsonr(potions_making, time_to_read)
print(f"Коэффициент корреляции Пирсона для времени на чтение: {correlation_time}")
print(f"P-значение для времени на чтение: {p_value_время}")

Коэффициент корреляции Пирсона: 0.8604309824577913
P-значение: 0.027859897904197198
Коэффициент корреляции Пирсона для времени на чтение: 0.9941002434954167
P-значение для времени на чтение: 5.2108013433647874e-05