In [ ]:
# Удаление пропущенных значений
df = df.dropna(subset=['ds', 'y'])
df = df.sort_values('ds').reset_index(drop=True)

data_train.tail(-5) и head

In [39]:
# Скачать и запустить Docker образ с ETNA и torch
!docker pull ghcr.io/tinkoff-ai/etna/etna-cpu:latest
!docker run -p 8888:8888 ghcr.io/tinkoff-ai/etna/etna-cpu:latest

latest: Pulling from tinkoff-ai/etna/etna-cpu

b88d5577: Pulling fs layer
16e23423: Pulling fs layer
7578c172: Pulling fs layer
a27109a8: Pulling fs layer
fcf5deff: Pulling fs layer
f141370c: Pulling fs layer
9436828c: Pulling fs layer
12ff574d: Pulling fs layer
e3b0b9c0: Pull complete   93B/93B.7MBBDigest: sha256:ea9b8ce196c19e8f6ca3f641ba6b4a094e8a96439e26eeb68190344abe90c215
Status: Downloaded newer image for ghcr.io/tinkoff-ai/etna/etna-cpu:latest
ghcr.io/tinkoff-ai/etna/etna-cpu:latest

In [44]:
!docker run -p 8888:8888 ghcr.io/tinkoff-ai/etna/etna-cpu:latest

_ = если два графика отображаются (в ВС коде один)
_ = plot_acf(original_df.target, lags=60)
plt.grid()

In [43]:
import etna
from etna.models.nn import DeepARModel, PytorchForecastingDatasetBuilder

print("ETNA version:", etna.__version__)
print("DeepAR доступен:", DeepARModel is not None)

ImportError: cannot import name 'PytorchForecastingDatasetBuilder' from 'etna.models.nn' (/usr/local/python/3.12.1/lib/python3.12/site-packages/etna/models/nn/__init__.py)

In [ ]:
print(model.summary())

In [ ]:
print(model.params()) ????

Тесты Дики-Фуллера (ADF) и KPSS

Полагаться только на визуальный анализ рискованно — иногда тренд или сезонность могут быть не так очевидны. Чтобы принять объективное решение, используют статистические тесты. Самый популярный из них — расширенный тест Дики-Фуллера (Augmented Dickey-Fuller Test, ADF).

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
import math #### все функции
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, roc_curve
from IPython.display import display, HTML
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier

from sympy import *

import mpl_toolkits.mplot3d as p3
import random
import time


from functools import partial
#from ipywidgets import interact, RadioButtons, IntSlider, FloatSlider, Dropdown, BoundedFloatText
from numpy.linalg import norm

from scipy import sparse

random.seed(42) # начальное состояние генератора случайных чисел, чтобы можно было воспроизводить результаты.

#!unzip «путь_до_архива»
#Всё извлечётся в память Colab.

In [3]:
# plotting
import scipy.stats as sps
import matplotlib.pyplot as plt
import seaborn as sns

# не ЕTNA модели Prophet, TBATS, SARIMAX — модели для предсказания временных рядов
import statsmodels

# metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error

# models
from tbats import TBATS
from prophet import Prophet
from pmdarima import auto_arima

# make plots bigger
from pylab import rcParams
rcParams['figure.figsize'] = 15, 7

In [4]:
import pandas as pd
import numpy as np

from etna.datasets.tsdataset import TSDataset

# модели
from etna.models import (NaiveModel, 
                         MovingAverageModel, 
                         SeasonalMovingAverageModel,
                         HoltWintersModel)

from etna.models import ProphetModel
from etna.models import CatBoostMultiSegmentModel


from etna.pipeline import Pipeline


from etna.metrics import MAE, MSE, SMAPE, MAPE

# аналитика
from etna.analysis import plot_forecast
from etna.analysis import plot_backtest
from etna.analysis import plot_feature_relevance
from etna.analysis import ModelRelevanceTable
from statsmodels.graphics.tsaplots import plot_acf

# трансформации
from etna.transforms import MeanTransform, LagTransform
from sklearn.ensemble import RandomForestRegressor


%config InlineBackend.figure_format = 'retina'

import warnings
warnings.filterwarnings('ignore')

In [1]:
import warnings

warnings.filterwarnings("ignore")
import random

import numpy as np
import pandas as pd
import torch

from etna.analysis import plot_backtest
from etna.datasets.tsdataset import TSDataset
from etna.metrics import MAE
from etna.metrics import MAPE
from etna.metrics import SMAPE
from etna.models import SeasonalMovingAverageModel
from etna.pipeline import Pipeline
from etna.transforms import DateFlagsTransform
from etna.transforms import LagTransform
from etna.transforms import LinearTrendTransform


metrics = [SMAPE(), MAPE(), MAE()]

In [ ]:
# для повторения исх данных для разных моделей
def set_seed(seed: int = 42):
    """Set random seed for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

In [33]:
HORIZON = 7
metrics = [SMAPE(), MAPE(), MAE()]

In [5]:
original_df = pd.read_csv("/workspaces/pyt_begin/data_data/data_T/example_dataset.csv")
original_df

       timestamp    segment  target
0     2019-01-01  segment_a     170
1     2019-01-02  segment_a     243
2     2019-01-03  segment_a     267
3     2019-01-04  segment_a     287
4     2019-01-05  segment_a     279
...          ...        ...     ...
1331  2019-11-26  segment_d     941
1332  2019-11-27  segment_d     949
1333  2019-11-28  segment_d     896
1334  2019-11-29  segment_d     905
1335  2019-11-30  segment_d     721

[1336 rows x 3 columns]

In [ ]:
df = TSDataset.to_dataset(original_df)
ts = TSDataset(df, freq="D")

segment    segment_a segment_b segment_c segment_d
feature       target    target    target    target
timestamp
2019-01-01     170.0     102.0      92.0     238.0
2019-01-02     243.0     123.0     107.0     358.0
2019-01-03     267.0     130.0     103.0     366.0
2019-01-04     287.0     138.0     103.0     385.0
2019-01-05     279.0     137.0     104.0     384.0

In [7]:
ts

segment    segment_a segment_b segment_c segment_d
feature       target    target    target    target
timestamp
2019-01-01     170.0     102.0      92.0     238.0
2019-01-02     243.0     123.0     107.0     358.0
2019-01-03     267.0     130.0     103.0     366.0
2019-01-04     287.0     138.0     103.0     385.0
2019-01-05     279.0     137.0     104.0     384.0
...              ...       ...       ...       ...
2019-11-26     591.0     259.0     196.0     941.0
2019-11-27     606.0     264.0     196.0     949.0
2019-11-28     555.0     242.0     207.0     896.0
2019-11-29     581.0     247.0     186.0     905.0
2019-11-30     502.0     206.0     169.0     721.0

[334 rows x 4 columns]

In [9]:
!pip install torch pytorch-forecasting

Requirement already satisfied: torch in /home/codespace/.local/lib/python3.12/site-packages (2.9.0+cpu)
Collecting pytorch-forecasting
  Downloading pytorch_forecasting-1.6.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (2025.9.0)
Requirement already satisfied: numpy<=3.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (2.2.0)
Requirement already satisfied: lightning<2.7.0,>=2.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (2.6.1)
Requirement already satisfied: scipy<2.0,>=1.8 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (1.15.3)
Requirement already satisfied: pandas<3.0.0,>=1.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from pytorch-forecasting) (2.3.3)
Requirement already satisfied: scikit-learn<2.0,>=1.2 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (1.8.0)
Collecting scikit-base<0.14.0 (from pytorch-forecasting)
  Downloading scikit_base-0.13.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: PyYAML<8.0,>5.4 in /home/codespace/.local/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (6.0.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (0.15.2)
Requirement already satisfied: packaging<27.0,>=23.0 in /home/codespace/.local/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (25.0)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.8.2)
Requirement already satisfied: tqdm<6.0,>=4.57.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (4.67.1)
Requirement already satisfied: pytorch-lightning in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/codespace/.python/current/lib/python3.12/site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (3.13.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.2)
Requirement already satisfied: joblib>=1.3.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.22.0)
Requirement already satisfied: idna>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (3.11)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=1.3.0->pytorch-forecasting) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from jinja2->torch) (2.1.5)
Downloading pytorch_forecasting-1.6.1-py3-none-any.whl (399 kB)
Downloading scikit_base-0.13.1-py3-none-any.whl (159 kB)
Installing collected packages: scikit-base, pytorch-forecasting
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pytorch-forecasting]torch-forecasting]
Successfully installed pytorch-forecasting-1.6.1 scikit-base-0.13.1

In [15]:
!pip uninstall etna pytorch-forecasting torch -y
!pip install torch --index-url https://download.pytorch.org/whl/cpu  # для CPU
!pip install pytorch-forecasting
!pip install "etna[torch]"

Found existing installation: etna 3.0.0
Uninstalling etna-3.0.0:
  Successfully uninstalled etna-3.0.0
Found existing installation: pytorch-forecasting 1.6.1
Uninstalling pytorch-forecasting-1.6.1:
  Successfully uninstalled pytorch-forecasting-1.6.1
Found existing installation: torch 2.9.0+cpu
Uninstalling torch-2.9.0+cpu:
  Successfully uninstalled torch-2.9.0+cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (2025.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from jinja2->torch) (2.1.5)
Downloading https://download.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl (188.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.9/188.9 MB 39.6 MB/s  0:00:04m0:00:0100:01
Installing collected packages: torch
Successfully installed torch-2.10.0+cpu
Collecting pytorch-forecasting
  Using cached pytorch_forecasting-1.6.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<=3.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (2.2.0)
Requirement already satisfied: torch!=2.0.1,<3.0.0,>=2.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (2.10.0+cpu)
Requirement already satisfied: lightning<2.7.0,>=2.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (2.6.1)
Requirement already satisfied: scipy<2.0,>=1.8 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (1.15.3)
Requirement already satisfied: pandas<3.0.0,>=1.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from pytorch-forecasting) (2.3.3)
Requirement already satisfied: scikit-learn<2.0,>=1.2 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (1.8.0)
Requirement already satisfied: scikit-base<0.14.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from pytorch-forecasting) (0.13.1)
Requirement already satisfied: PyYAML<8.0,>5.4 in /home/codespace/.local/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (6.0.3)
Requirement already satisfied: fsspec<2028.0,>=2022.5.0 in /home/codespace/.local/lib/python3.12/site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (2025.9.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (0.15.2)
Requirement already satisfied: packaging<27.0,>=23.0 in /home/codespace/.local/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (25.0)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.8.2)
Requirement already satisfied: tqdm<6.0,>=4.57.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (4.67.1)
Requirement already satisfied: typing-extensions<6.0,>4.5.0 in /home/codespace/.local/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (4.15.0)
Requirement already satisfied: pytorch-lightning in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning<2.7.0,>=2.0.0->pytorch-forecasting) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/codespace/.python/current/lib/python3.12/site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (3.13.3)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from lightning-utilities<2.0,>=0.10.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (80.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=1.3.0->pytorch-forecasting) (2025.2)
Requirement already satisfied: joblib>=1.3.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from scikit-learn<2.0,>=1.2->pytorch-forecasting) (3.6.0)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (3.19.1)
Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (3.5)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (3.1.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (1.22.0)
Requirement already satisfied: idna>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning<2.7.0,>=2.0.0->pytorch-forecasting) (3.11)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=1.3.0->pytorch-forecasting) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from jinja2->torch!=2.0.1,<3.0.0,>=2.0.0->pytorch-forecasting) (2.1.5)
Using cached pytorch_forecasting-1.6.1-py3-none-any.whl (399 kB)
Installing collected packages: pytorch-forecasting
Successfully installed pytorch-forecasting-1.6.1
ERROR: Could not find a version that satisfies the requirement etna[torch] (from versions: none)
ERROR: No matching distribution found for etna[torch]

In [18]:
!pip install torch --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Requirement already satisfied: torch in /home/codespace/.python/current/lib/python3.12/site-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/codespace/.local/lib/python3.12/site-packages (from torch) (2025.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from jinja2->torch) (2.1.5)

In [20]:
!pip install "etna[torch]@git+https://github.com/etna-team/etna.git@master"

Collecting etna @ git+https://github.com/etna-team/etna.git@master (from etna[torch] @ git+https://github.com/etna-team/etna.git@master)
  Cloning https://github.com/etna-team/etna.git (to revision master) to /tmp/pip-install-xku4pfgl/etna_d5dbc93b402f4f4286f47dfff7d355fe
  Running command git clone --filter=blob:none --quiet https://github.com/etna-team/etna.git /tmp/pip-install-xku4pfgl/etna_d5dbc93b402f4f4286f47dfff7d355fe
  Resolved https://github.com/etna-team/etna.git to commit c8e41911637c90e451e6f2bcc29f31d81bafab02
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Bottleneck<2.0.0,>=1.3.4 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.6.0)
Requirement already satisfied: Deprecated==1.2.13 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.2.13)
Requirement already satisfied: boto3<2.0,>=1.5 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.42.49)
Requirement already satisfied: botocore in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.42.49)
Requirement already satisfied: catboost<2,>=1 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.2.8)
Requirement already satisfied: dill<0.4.0,>=0.3.4 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.3.9)
Requirement already satisfied: holidays>=0.40 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.90)
Requirement already satisfied: hydra-slayer>=0.5 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.5.0)
Requirement already satisfied: joblib in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.5.3)
Requirement already satisfied: loguru>=0.7 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.7.3)
Requirement already satisfied: matplotlib in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.10.8)
Requirement already satisfied: numba>=0.53.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.62.1)
Collecting numpy<2 (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master)
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: omegaconf<3.0.0,>=2.1.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.3.0)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.3.3)
Requirement already satisfied: plotly<6 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (5.24.1)
Requirement already satisfied: pmdarima>=2.0.4 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.1.1)
Requirement already satisfied: ruptures<2.0.0,>=1.1.5 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.1.10)
Requirement already satisfied: scikit-learn<2,>=1.4 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.8.0)
Requirement already satisfied: scipy>=1.12 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.15.3)
Requirement already satisfied: seaborn<1,>=0.11.1 in /home/codespace/.local/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.13.2)
Requirement already satisfied: statsmodels<0.15,>=0.14 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.14.6)
Requirement already satisfied: tbats<2.0.0,>=1.1.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.1.3)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.10.2)
Requirement already satisfied: typer>=0.12 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.23.1)
Requirement already satisfied: types-Deprecated==1.2.9 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.2.9)
Requirement already satisfied: typing_extensions<5.0.0,>=4.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (4.15.0)
Requirement already satisfied: einops in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.8.2)
Requirement already satisfied: lightning in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.6.1)
Requirement already satisfied: torch<3,>=2 in /home/codespace/.python/current/lib/python3.12/site-packages (from etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.10.0+cpu)
Requirement already satisfied: wrapt<2,>=1.10 in /home/codespace/.python/current/lib/python3.12/site-packages (from Deprecated==1.2.13->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.17.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from boto3<2.0,>=1.5->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from boto3<2.0,>=1.5->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/codespace/.local/lib/python3.12/site-packages (from botocore->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /home/codespace/.local/lib/python3.12/site-packages (from botocore->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.5.0)
Requirement already satisfied: graphviz in /home/codespace/.python/current/lib/python3.12/site-packages (from catboost<2,>=1->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.21)
Requirement already satisfied: six in /home/codespace/.local/lib/python3.12/site-packages (from catboost<2,>=1->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.17.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /home/codespace/.python/current/lib/python3.12/site-packages (from omegaconf<3.0.0,>=2.1.1->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from omegaconf<3.0.0,>=2.1.1->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (6.0.3)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=2.0.0->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas<3.0.0,>=2.0.0->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from plotly<6->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (9.1.4)
Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.12/site-packages (from plotly<6->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (25.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from scikit-learn<2,>=1.4->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /home/codespace/.python/current/lib/python3.12/site-packages (from statsmodels<0.15,>=0.14->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.0.2)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.19.1)
Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.5)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/codespace/.local/lib/python3.12/site-packages (from torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2025.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.2.5)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /home/codespace/.python/current/lib/python3.12/site-packages (from numba>=0.53.1->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.45.1)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /home/codespace/.python/current/lib/python3.12/site-packages (from pmdarima>=2.0.4->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.2.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.3.0)
Requirement already satisfied: click>=8.0.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (14.3.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/codespace/.python/current/lib/python3.12/site-packages (from typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from rich>=10.11.0->typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/codespace/.local/lib/python3.12/site-packages (from rich>=10.11.0->typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/codespace/.python/current/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.12->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from jinja2->torch<3,>=2->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.1.5)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (0.15.2)
Requirement already satisfied: torchmetrics<3.0,>0.7.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.8.2)
Requirement already satisfied: tqdm<6.0,>=4.57.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (4.67.1)
Requirement already satisfied: pytorch-lightning in /home/codespace/.python/current/lib/python3.12/site-packages (from lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/codespace/.python/current/lib/python3.12/site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (3.13.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/codespace/.python/current/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning->etna @ git+https://github.com/etna-team/etna.git@master->etna[torch] @ git+https://github.com/etna-team/etna.git@master) (1.4.0)

In [22]:
import etna
print(f"ETNA version: {etna.__version__}")

AttributeError: module 'etna' has no attribute '__version__'

In [30]:
import etna.models.nn.utils
print("Доступные классы в etna.models.nn:")
print([item for item in dir(etna.models.nn.utils) if not item.startswith('_')])

Доступные классы в etna.models.nn:
['Dict', 'MultiEmbedding', 'SETTINGS', 'Tuple', 'nn', 'torch']

In [40]:
from etna.models.nn import PytorchForecastingDatasetBuilder

ImportError: cannot import name 'PytorchForecastingDatasetBuilder' from 'etna.models.nn' (/usr/local/python/3.12.1/lib/python3.12/site-packages/etna/models/nn/__init__.py)

In [35]:
from etna.models.nn import DeepARModel

In [41]:
from etna.models.nn import DeepARNativeModel
from etna.transforms import StandardScalerTransform

ImportError: cannot import name 'DeepARNativeModel' from 'etna.models.nn' (/usr/local/python/3.12.1/lib/python3.12/site-packages/etna/models/nn/__init__.py)

In [31]:
set_seed()

In [37]:
model_deepar = DeepARModel(
    encoder_length=HORIZON,
    decoder_length=HORIZON,
    trainer_params=dict(max_epochs=150, gpus=0, gradient_clip_val=0.1),
    lr=0.01,
    train_batch_size=64,
)
metrics = [SMAPE(), MAPE(), MAE()]

pipeline_deepar = Pipeline(model=model_deepar, horizon=HORIZON)

TypeError: DeepARModel.__init__() missing 1 required positional argument: 'input_size'

In [38]:
dataset_builder = PytorchForecastingDatasetBuilder(
    max_encoder_length=30,
    max_prediction_length=14,
    time_varying_known_reals=['time_idx'],
    time_varying_unknown_reals=['target'],
    static_categoricals=None,
    static_reals=None
)

NameError: name 'PytorchForecastingDatasetBuilder' is not defined